from . import bcat, dpot, morph, mpp, pdeformer2, poseidon, prose, walrus
from . import layers
from .pipe import block, Block, Pipe, ShapeMismatchError
from .combinators import dot, add, cat
from .nn import (
    # non-foundation architectures
    linear,
    mlp,
    fno1d,
    fno2d,
    fno3d,
    unet1d,
    unet2d,
    unet3d,
    transformer,
    deeponet,
    cno2d,
    mgno1d,
    mgno2d,
    geofno,
    pcno,
    cgptno,
    gnot,
    moegptno,
    pit,
    pointnet,
    # KAN family
    kan,
    efficient_kan,
    fastkan,
    fourier_kan,
    chebyshev_kan,
    jacobi_kan,
    legendre_kan,
    wavelet_kan,
    taylor_kan,
    hermite_kan,
    laguerre_kan,
    bernstein_kan,
    relu_kan,
    rational_kan,
    sinc_kan,
    gram_kan,
    bsrbf_kan,
    kan_conv1d,
    kan_conv2d,
    kan_conv3d,
    kan_res_block,
    kan_spectral_block1d,
    kan_spectral_block2d,
    kan_spectral_block3d,
    kan_attention_block,
    # foundation model shortcuts
    poseidonT,
    poseidonB,
    poseidonL,
    morph_Ti,
    morph_S,
    morph_M,
    morph_L,
    mpp_Ti,
    mpp_S,
    mpp_B,
    mpp_L,
    pdeformer2_small,
    pdeformer2_base,
    pdeformer2_fast,
    dpot_Ti,
    dpot_S,
    dpot_M,
    dpot_L,
    dpot_H,
    prose_fd_1to1,
    prose_fd_2to1,
    prose_ode_2to1,
    prose_pde_2to1,
)

__version__ = "0.2.0"

__all__ = [
    "__version__",
    # pipe API
    "block",
    "Block",
    "Pipe",
    "ShapeMismatchError",
    # combinators
    "dot",
    "add",
    "cat",
    # composable layers subpackage
    "layers",
    # submodule namespaces
    "poseidon",
    "walrus",
    "morph",
    "mpp",
    "bcat",
    "pdeformer2",
    "dpot",
    "prose",
    # architecture factories
    "linear",
    "mlp",
    "fno1d",
    "fno2d",
    "fno3d",
    "unet1d",
    "unet2d",
    "unet3d",
    "transformer",
    "deeponet",
    "cno2d",
    "mgno1d",
    "mgno2d",
    "geofno",
    "pcno",
    "cgptno",
    "gnot",
    "moegptno",
    "pit",
    "pointnet",
    # KAN family
    "kan",
    "efficient_kan",
    "fastkan",
    "fourier_kan",
    "chebyshev_kan",
    "jacobi_kan",
    "legendre_kan",
    "wavelet_kan",
    "taylor_kan",
    "hermite_kan",
    "laguerre_kan",
    "bernstein_kan",
    "relu_kan",
    "rational_kan",
    "sinc_kan",
    "gram_kan",
    "bsrbf_kan",
    "kan_conv1d",
    "kan_conv2d",
    "kan_conv3d",
    "kan_res_block",
    "kan_spectral_block1d",
    "kan_spectral_block2d",
    "kan_spectral_block3d",
    "kan_attention_block",
    # foundation model factories
    "poseidonT",
    "poseidonB",
    "poseidonL",
    "morph_Ti",
    "morph_S",
    "morph_M",
    "morph_L",
    "mpp_Ti",
    "mpp_S",
    "mpp_B",
    "mpp_L",
    "pdeformer2_small",
    "pdeformer2_base",
    "pdeformer2_fast",
    "dpot_Ti",
    "dpot_S",
    "dpot_M",
    "dpot_L",
    "dpot_H",
    "prose_fd_1to1",
    "prose_fd_2to1",
    "prose_ode_2to1",
    "prose_pde_2to1",
]
